In [103]:
import numpy as np
import matplotlib.pyplot as plt
#plt.imshow(f)
#plt.imshow()

In [5]:
a = list(range(10))
fun = lambda x : np.sin(x)
a.sort(key = fun)
print(a)
print([fun(x) for x in a])

[5, 4, 6, 0, 3, 9, 7, 1, 2, 8]
[-0.9589242746631385, -0.7568024953079282, -0.27941549819892586, 0.0, 0.1411200080598672, 0.4121184852417566, 0.6569865987187891, 0.8414709848078965, 0.9092974268256817, 0.9893582466233818]


In [10]:
a1 = np.arange(1, 21)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [74]:
print(np.reshape(a1, [2, 10]))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [73]:
print(np.reshape(a1, [2, 10], order = 'F'))

[[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]]


In [70]:
print(np.reshape(a1, [4, 5], order = 'F'))

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


In [72]:
print(np.reshape(a1, (5,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [23]:
b1 = np.arange(1, 10)
b1.reshape(3,3)
print(b1)

[1 2 3 4 5 6 7 8 9]


In [25]:
b2 = np.reshape(b1, [3,3])
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(np.round(b2 / 9, 1))

[[0.1 0.2 0.3]
 [0.4 0.6 0.7]
 [0.8 0.9 1. ]]


In [52]:
print(b2 * np.reshape(np.arange(-1,2),(1,3)))

[[-1  0  3]
 [-4  0  6]
 [-7  0  9]]


In [63]:
print(np.round(b2 / np.reshape(np.arange(3,12,3),(3,1)),1))

[[0.3 0.7 1. ]
 [0.7 0.8 1. ]
 [0.8 0.9 1. ]]


In [64]:
print(np.reshape(np.arange(1,4),(1,3))*np.reshape(np.arange(1,4),(3,1)))

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [26]:
c1 = np.arange(1,17)
print(c1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [29]:
c2 = c1.reshape(1,16)
print(c2)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [31]:
c3 = c2.reshape(4,4, order = 'F')
print(c3)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [32]:
c4 = c3.T
print(c4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
c5 = np.reshape(c4.T, (16,1))
print(c5)

[[ 1]
 [ 5]
 [ 9]
 [13]
 [ 2]
 [ 6]
 [10]
 [14]
 [ 3]
 [ 7]
 [11]
 [15]
 [ 4]
 [ 8]
 [12]
 [16]]


In [81]:
print(np.reshape(np.arange(1,13),(3,4)))
print(np.reshape(np.arange(1,7),(3,2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [3 4]
 [5 6]]


In [83]:
d1 = np.concatenate([np.reshape(np.arange(1,13),(3,4)), np.reshape(np.arange(1,7),(3,2))], axis = 1)
print(d1)

[[ 1  2  3  4  1  2]
 [ 5  6  7  8  3  4]
 [ 9 10 11 12  5  6]]


In [85]:
print(np.split(d1, [4], axis = 1))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[1, 2],
       [3, 4],
       [5, 6]])]


In [87]:
print(np.split(d1, [3, 4], axis = 1))

[array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]]), array([[ 4],
       [ 8],
       [12]]), array([[1, 2],
       [3, 4],
       [5, 6]])]


In [88]:
print(np.split(d1, [2, 4], axis = 1))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]]), array([[1, 2],
       [3, 4],
       [5, 6]])]


In [95]:
d2, d3, d4 = np.split(d1, [2, 4], axis = 1)
print(d2, d3, d4, sep = '\n')

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[1 2]
 [3 4]
 [5 6]]


In [96]:
e1 = np.reshape(np.arange(1,10),(3,3))
e2 = np.reshape(np.arange(1,18,2),(3,3))
print(e1, e2, sep = '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [97]:
e3 = np.concatenate([e1, e2], axis = 0)
print(e3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [100]:
e4, e5, e6, e7 = np.split(e3, [1,3,5], axis = 0)
print(e4, e5, e6, e7, sep = '\n')

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[ 1  3  5]
 [ 7  9 11]]
[[13 15 17]]


In [102]:
e8 = np.tile(e6, (2,5))
print(e8)

[[ 1  3  5  1  3  5  1  3  5  1  3  5  1  3  5]
 [ 7  9 11  7  9 11  7  9 11  7  9 11  7  9 11]
 [ 1  3  5  1  3  5  1  3  5  1  3  5  1  3  5]
 [ 7  9 11  7  9 11  7  9 11  7  9 11  7  9 11]]


In [ ]:
f1 = 